Repository wordpress-mobile/MediaPicker-iOS, pull requests merged in 2022-01, with the labels that each got.

#376 PHPhotoLibrary: Register change observer after asking for permission
  Pod/Classes/WPPHAssetDataSource.m
Labels: bug

#378 Update the release to version 1.8.1
  CHANGELOG.md
  WPMediaPicker.podspec
Labels: Releases

#379 Add support for custom header views
  Example/WPMediaPicker.xcodeproj/project.pbxproj
  Example/WPMediaPicker/DemoViewController.m
  Example/WPMediaPicker/OptionsViewController.h
  Example/WPMediaPicker/OptionsViewController.m
  Example/WPMediaPicker/SampleCustomHeaderView.h
  Example/WPMediaPicker/SampleCustomHeaderView.m
  Pod/Classes/WPMediaPickerViewController.h
  Pod/Classes/WPMediaPickerViewController.m
  Pod/Classes/WPNavigationMediaPickerViewController.m
  WPMediaPicker.podspec
Labels: enhancement

#380 Invalidate custom header layout if trait collection changes
  Pod/Classes/WPMediaPickerViewController.m
  WPMediaPicker.podspec
Labels: enhancement
